### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by name01019** [Cartmanishere/zippyshare-scraper#10]
Traceback (most recent call last):
  File "zippyshare.py", line 290, in <module>
    links = zippy.parse_links(urls)
  File "zippyshare.py", line 131, in parse_links
    extract, link = f.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "zippyshare.py", line 76, in get_download_link
    extract = self.pattern_1(soup)
  File "zippyshare.py", line 180, in pattern_1
    a = math.floor(a / 3)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by Cartmanishere** [comment]
Fixed.
