### ISSUE TITLE
Script suddenly stopped working

### ISSUE THREAD

**Issue by Aaron34789** [Cartmanishere/zippyshare-scraper#4]
Firstly would like to thank for the program, Script stopped working today. Receiving below errors:

C:\Users\Test>C:\Users\Test\Zippyshare\zippyshare_3.py
File(f) | List(l) | dlcfile (d)? f
File path: C:\Users\Test\Zippyshare\links.txt
File found. Beginning scraping.
Total Links = 1
Traceback (most recent call last):
  File "C:\Users\Test\Zippyshare\zippyshare_3.py", line 184, in <mod
ule>
    links = parser.do_main()
  File "C:\Users\Test\Zippyshare\zippyshare_3.py", line 24, in do_ma
in
    extract, status = self.parse_link(i)
  File "C:\Users\Test\Zippyshare\zippyshare_3.py", line 155, in pars
e_link
    d = self.get_value_of_d()
  File "C:\Users\Test\Zippyshare\zippyshare_3.py", line 179, in get_
value_of_d
    return int(self.soup.select('span[id="omg"]')[0].get('class')[0]) * 2
IndexError: list index out of range

**Comment by Exodion** [comment]
Having the same issue here. Using Python 3.7.2.
`[linux@Arch zippyshare-scraper]$ python zippyshare_3.py 
File(f) | List(l) | dlcfile (d)? f
File path: 1.txt
File found. Beginning scraping.
Total Links = 98
Traceback (most recent call last):
  File "zippyshare_3.py", line 184, in <module>
    links = parser.do_main()
  File "zippyshare_3.py", line 24, in do_main
    extract, status = self.parse_link(i)
  File "zippyshare_3.py", line 155, in parse_link
    d = self.get_value_of_d()
  File "zippyshare_3.py", line 179, in get_value_of_d
    return int(self.soup.select('span[id="omg"]')[0].get('class')[0]) * 2
IndexError: list index out of range`

**Comment by Exodion** [comment]
Having the same issue here. Using Python 3.7.2.

[arch@linux zippyshare-scraper]$ python zippyshare_3.py 
File path: 1.txt
File found. Beginning scraping.
Total Links = 98
Traceback (most recent call last):
  File "zippyshare_3.py", line 184, in <module>
    links = parser.do_main()
  File "zippyshare_3.py", line 24, in do_main
    extract, status = self.parse_link(i)
  File "zippyshare_3.py", line 155, in parse_link
    d = self.get_value_of_d()
  File "zippyshare_3.py", line 179, in get_value_of_d
    return int(self.soup.select('span[id="omg"]')[0].get('class')[0]) * 2
IndexError: list index out of range

**Comment by Exodion** [comment]
@Aaron34789 @Cartmanishere Issue is fixed now. Thanks.

**Comment by Aaron34789** [comment]
Thank you @Exodion  It's working now!!
