### ISSUE TITLE
No links being scraped

### ISSUE THREAD

**Issue by Exodion** [Cartmanishere/zippyshare-scraper#6]
Hey man. This could be a problem on zippyshare's end but I'm still creating an issue since I need this script to work 24/7. Using Python 3.7.2 on Linux and 3.6.5 on Windows 10, getting the same issue on both ends. My network is working. Nothing is being scraped, I've waited for a timeout but there is none. It just waits there forever until I Ctrl-C. Here is the output. 

[arch@linux zippyshare-scraper]$ python zippyshare_1.py
File(f) | List(l) | dlcfile (d)? f
File path: 1.txt
File found. Beginning scraping.
Total Links = 2
^CTraceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zippyshare_1.py", line 177, in <module>
    links = parser.do_main()
  File "zippyshare_1.py", line 26, in do_main
    p, count = self.remove_redirects(p)
  File "zippyshare_1.py", line 107, in remove_redirects
    p = self._session.get(new_link, headers=headers)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

**Comment by Cartmanishere** [comment]
Hi,

Please try the updated version of my script `zippyshare_1.py`.

**Comment by Exodion** [comment]
@Cartmanishere Working again. Thanks mate.
